# Generated by Django 4.2.7 on 2026-05-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/')),
                ('primary_color', models.CharField(default='#2563EB', max_length=7)),
                ('secondary_color', models.CharField(default='#1E40AF', max_length=7)),
                ('accent_color', models.CharField(default='#10B981', max_length=7)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise'), ('trial', 'Free Trial')], default='trial', max_length=20)),
                ('plan_started_at', models.DateTimeField(blank=True, null=True)),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('trial', 'Trial'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('allow_student_self_registration', models.BooleanField(default=False)),
                ('require_invitation_code', models.BooleanField(default=True)),
                ('enable_peer_support', models.BooleanField(default=True)),
                ('enable_group_sessions', models.BooleanField(default=True)),
                ('max_session_duration_minutes', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'ordering': ['name'],
            },
        ),
    ]
